A-allocator:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_allocator/**"]

A-ast:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_ast/**"]

A-ast-tools:
  - changed-files:
      - any-glob-to-any-file: ["tasks/ast_tools/**"]

A-cfg:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_cfg/**"]

A-cli:
  - changed-files:
      - any-glob-to-any-file: ["apps/goatlint/**", "apps/goatfmt/**"]

A-editor:
  - changed-files:
      - any-glob-to-any-file:
          ["crates/goat_language_server/**", "apps/goatlint/src/lsp/**", "apps/goatfmt/src/lsp/**"]

A-formatter:
  - changed-files:
      - any-glob-to-any-file:
          ["crates/goat_formatter/**", "tasks/prettier_conformance/**", "apps/goatfmt/**"]

A-transformer:
  - changed-files:
      - any-glob-to-any-file:
          ["crates/goat_transformer/**", "tasks/transform_conformance/**", "napi/transform/**"]

A-linter:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_linter/**", "apps/goatlint/**"]

A-linter-plugins:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/goatlint/src-js/**", "apps/goatlint/test/**", "apps/goatlint/conformance/**"]

A-minifier:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_minifier/**", "napi/minify/**"]

A-parser:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_parser/**", "napi/parser/**"]

A-codegen:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_codegen/**"]

A-semantic:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_semantic/**"]

A-type-checking:
  - changed-files:
      - any-glob-to-any-file: ["crates/oxc_type_synthesis/**"]

A-isolated-declarations:
  - changed-files:
      - any-glob-to-any-file: ["crates/goat_isolated_declarations/**"]
