# Configuration file for [cargo release oxc](https://github.com/goat-project/cargo-release-oxc)

# Release `--name crates`
[[releases]]
name = "crates"
root_crate = "goat"
versioned_files = [
  "Cargo.toml",
  "napi/parser/package.json",
  "napi/transform/package.json",
  "napi/minify/package.json",
  "npm/goat-types/package.json",
  "npm/runtime/package.json",
]

[[releases]]
name = "goatlint"
scopes_for_breaking_change = ["lint"]
versioned_files = [
  "apps/goatlint/Cargo.toml",
  "apps/goatlint/package.json",
  "crates/goat_linter/Cargo.toml",
  "npm/goatlint/package.json",
  "npm/goatlint-plugin-eslint/package.json",
  "npm/goatlint-plugins/package.json",
]

[[releases]]
name = "goatfmt"
scopes_for_breaking_change = ["format"]
versioned_files = [
  "apps/goatfmt/Cargo.toml",
  "apps/goatfmt/package.json",
  "crates/goat_formatter/Cargo.toml",
  "npm/goatfmt/package.json",
]
