[package]
name = "goat_mangler"
version = "0.124.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/examples", "/src"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
test = true

[dependencies]
goat_allocator = { workspace = true, features = ["bitset"] }
goat_ast = { workspace = true }
goat_data_structures = { workspace = true, features = ["inline_string"] }
oxc_index = { workspace = true }
goat_semantic = { workspace = true }
goat_span = { workspace = true }
goat_syntax = { workspace = true }

itertools = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
goat_parser = { workspace = true }
