[package]
name = "goat_prettier_conformance"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[bin]]
name = "goat_prettier_conformance"
path = "src/main.rs"
test = false
doctest = false

[dependencies]
goat_allocator = { workspace = true }
goat_ast = { workspace = true }
goat_ast_visit = { workspace = true }
goat_formatter = { workspace = true }
goat_parser = { workspace = true }
goat_span = { workspace = true }
goat_tasks_common = { workspace = true }

cow-utils = { workspace = true }
pico-args = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
walkdir = { workspace = true }
