[package]
name = "goat_traverse"
version = "0.125.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/src"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
test = true
# Doctests must be enabled for this crate as they are used to run tests
# which check the soundness of its code
doctest = true

[dependencies]
goat_allocator = { workspace = true }
goat_ast = { workspace = true }
goat_ast_visit = { workspace = true }
goat_data_structures = { workspace = true, features = ["stack"] }
goat_ecmascript = { workspace = true }
goat_semantic = { workspace = true }
goat_span = { workspace = true }
goat_str = { workspace = true }
goat_syntax = { workspace = true }

itoa = { workspace = true }
rustc-hash = { workspace = true }
