[package]
name = "goat_benchmark"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
test = false
bench = false
doctest = false

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "transformer"
harness = false

[[bench]]
name = "semantic"
harness = false

[[bench]]
name = "linter"
harness = false

[[bench]]
name = "codegen"
harness = false

[[bench]]
name = "formatter"
harness = false

[[bench]]
name = "minifier"
harness = false

[[bench]]
name = "pipeline"
harness = false

# Only run in CI
[[bench]]
name = "parser_napi"
harness = false
bench = false

# All `goat_*` dependencies optional as on CI we build each benchmark separately
# with only the crates it needs, to speed up the builds
[dependencies]
goat_allocator = { workspace = true, optional = true }
goat_ast = { workspace = true, optional = true, features = ["serialize"] }
goat_ast_visit = { workspace = true, optional = true, features = ["serialize"] }
goat_codegen = { workspace = true, optional = true, features = ["sourcemap"] }
goat_estree_tokens = { workspace = true, optional = true }
goat_formatter = { workspace = true, optional = true }
goat_isolated_declarations = { workspace = true, optional = true }
goat_linter = { workspace = true, optional = true }
goat_mangler = { workspace = true, optional = true }
goat_minifier = { workspace = true, optional = true }
goat_parser = { workspace = true, features = [
  "benchmarking",
  "regular_expression",
], optional = true }
goat_semantic = { workspace = true, optional = true }
goat_span = { workspace = true, optional = true, features = ["schemars", "serialize"] }
goat_tasks_common = { workspace = true, optional = true }
goat_transformer = { workspace = true, optional = true }

criterion2 = { workspace = true }

# Only for lexer benchmark
cow-utils = { workspace = true, optional = true }

# Only for NAPI benchmark
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["compiler", "linter"]
codspeed = ["criterion2/codspeed"]
codspeed_napi = ["criterion2/codspeed", "dep:serde", "dep:serde_json"]

# Features for running benchmarks with minimum dependencies.
# "compiler" feature includes: lexer, parser, transformer, semantic, minifier, codegen, formatter
# "linter" feature includes: linter
compiler = [
  "dep:goat_allocator",
  "dep:goat_ast",
  "dep:goat_ast_visit",
  "dep:goat_codegen",
  "dep:goat_estree_tokens",
  "dep:goat_formatter",
  "dep:goat_isolated_declarations",
  "dep:goat_mangler",
  "dep:goat_minifier",
  "dep:goat_parser",
  "dep:goat_semantic",
  "dep:goat_span",
  "dep:goat_tasks_common",
  "dep:goat_transformer",
  "dep:cow-utils",
]
linter = [
  "dep:goat_allocator",
  "dep:goat_linter",
  "dep:goat_parser",
  "dep:goat_semantic",
  "dep:goat_span",
  "dep:goat_tasks_common",
  "goat_semantic/cfg",
]

[dev-dependencies]
rustc-hash = { workspace = true }

[package.metadata.cargo-shear]
ignored = [
  "goat_allocator",
  "goat_ast",
  "goat_ast_visit",
  "goat_codegen",
  "goat_estree_tokens",
  "goat_formatter",
  "goat_isolated_declarations",
  "goat_linter",
  "goat_mangler",
  "goat_minifier",
  "goat_parser",
  "goat_semantic",
  "goat_span",
  "goat_tasks_common",
  "goat_transformer",
  "serde",
  "serde_json",
  "cow-utils",
]
