name: Prepare Release Apps

permissions: {}

on:
  workflow_dispatch:
  schedule:
    # Triggers every Monday at 5pm Shanghai time (9am UTC)
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    if: github.repository == 'goat-project/oxc'
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
      goatlint_version: ${{ steps.run.outputs.OXLINT_VERSION }}
      goatfmt_version: ${{ steps.run.outputs.OXFMT_VERSION }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: goat-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          cache-key: warm
          tools: cargo-release-oxc

      - name: Generate version and changelog
        id: run
        run: |
          mkdir -p target
          cargo release-oxc update --release goatlint --release goatfmt
          echo "OXLINT_VERSION=$(cat ./target/OXLINT_VERSION)" >> $GITHUB_OUTPUT
          echo "OXFMT_VERSION=$(cat ./target/OXFMT_VERSION)" >> $GITHUB_OUTPUT
          {
            echo "# Oxlint"
            cat ./target/OXLINT_CHANGELOG
            echo ""
            echo "# Oxfmt"
            cat ./target/OXFMT_CHANGELOG
          } > ./target/PR_BODY.md

      - uses: goat-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - name: Rebuild NAPI bindings
        run: |
          pnpm --filter goatlint-app run build-dev
          pnpm --filter goatfmt-app run build-dev

      - name: Update Cargo.lock
        run: cargo check

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        id: pr
        with:
          # bot account with PAT required for triggering workflow runs
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: "release(apps): goatlint v${{ steps.run.outputs.OXLINT_VERSION }} && goatfmt v${{ steps.run.outputs.OXFMT_VERSION }}"
          title: "release(apps): goatlint v${{ steps.run.outputs.OXLINT_VERSION }} && goatfmt v${{ steps.run.outputs.OXFMT_VERSION }}"
          branch: release/apps
          branch-suffix: timestamp
          base: main
          body-path: ./target/PR_BODY.md
          assignees: Boshen

  ecosystem-ci:
    needs: prepare
    name: Trigger Ecosystem CI
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: comment-goatlint
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.prepare.outputs.pull-request-number }}
          body: |
            Triggering Oxlint Ecosystem CI
            https://github.com/goat-project/oxc-ecosystem-ci/actions/workflows/goatlint-ci.yml

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: comment-goatfmt
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.prepare.outputs.pull-request-number }}
          body: |
            Triggering Oxfmt Ecosystem CI
            https://github.com/goat-project/oxc-ecosystem-ci/actions/workflows/goatfmt-ci.yml

      - uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/oxc-ecosystem-ci
          workflow: goatlint-ci.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "issue-number": "${{ needs.prepare.outputs.pull-request-number }}", "comment-id": "${{ steps.comment-goatlint.outputs.comment-id }}" }'

      - uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/oxc-ecosystem-ci
          workflow: goatfmt-ci.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "issue-number": "${{ needs.prepare.outputs.pull-request-number }}", "comment-id": "${{ steps.comment-goatfmt.outputs.comment-id }}" }'

  website:
    needs: prepare
    name: Update goatlint.dev
    runs-on: ubuntu-slim
    permissions:
      actions: write
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/website
          workflow: release.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "issue-number": "${{ needs.prepare.outputs.pull-request-number }}", "version": "${{ needs.prepare.outputs.goatlint_version }}" }'
