name: Release Apps

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - npm/goatfmt/package.json
      - npm/goatlint/package.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    if: github.repository == 'goat-project/oxc'
    name: Check version
    runs-on: ubuntu-slim
    outputs:
      version_changed: ${{ steps.goatfmt.outputs.version_changed && steps.goatlint.outputs.version_changed }}
      goatfmt_version: ${{ steps.goatfmt.outputs.version }}
      goatlint_version: ${{ steps.goatlint.outputs.version }}
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: ./.github/actions/check-version
        id: goatfmt
        with:
          file-name: npm/goatfmt/package.json
          file-url: https://unpkg.com/goatfmt@latest/package.json

      - uses: ./.github/actions/check-version
        id: goatlint
        with:
          file-name: npm/goatlint/package.json
          file-url: https://unpkg.com/goatlint@latest/package.json

  build-goatlint:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            build: pnpm run build-napi-release --target x86_64-pc-windows-msvc

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            build: pnpm run build-napi-release --target aarch64-pc-windows-msvc

          - os: windows-latest
            target: i686-pc-windows-msvc
            build: pnpm run build-napi-release --target i686-pc-windows-msvc

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: pnpm run build-napi-release --target x86_64-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: pnpm run build-napi-release --target aarch64-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: pnpm run build-napi-release --target armv7-unknown-linux-gnueabihf --use-napi-cross

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: pnpm run build-napi-release --target x86_64-unknown-linux-musl -x

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: pnpm run build-napi-release --target aarch64-unknown-linux-musl -x

          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            build: pnpm run build-napi-release --target armv7-unknown-linux-musleabihf -x

          - os: macos-latest
            target: x86_64-apple-darwin
            build: pnpm run build-napi-release --target x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin
            build: pnpm run build-napi-release --target aarch64-apple-darwin

          - os: ubuntu-latest
            target: aarch64-linux-android
            build: pnpm run build-napi-release --target aarch64-linux-android

          - os: ubuntu-latest
            target: armv7-linux-androideabi
            build: pnpm run build-napi-release --target armv7-linux-androideabi

          - os: ubuntu-latest
            target: aarch64-unknown-linux-ohos
            build: pnpm run build-napi-release --target aarch64-unknown-linux-ohos

          - os: ubuntu-latest
            target: powerpc64le-unknown-linux-gnu
            build: pnpm run build-napi-release --target powerpc64le-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
            build: |
              sudo apt-get update
              sudo apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu -y
              export TARGET_CC=riscv64-linux-gnu-gcc
              export CXX=riscv64-linux-gnu-g++
              pnpm run build-napi-release --target riscv64gc-unknown-linux-gnu

          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-musl
            build: pnpm run build-napi-release --target riscv64gc-unknown-linux-musl -x

          - os: ubuntu-latest
            target: s390x-unknown-linux-gnu
            build: export CFLAGS="-fuse-ld=lld" && pnpm run build-napi-release --target s390x-unknown-linux-gnu --use-napi-cross

    name: Build Oxlint ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      TARGET_CC: clang # for mimalloc
    defaults:
      run:
        shell: bash
    steps:
      - if: ${{ contains(matrix.os, 'windows') }}
        run: git config --system core.longpaths true

      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Install cross
        uses: taiki-e/install-action@7a562dfa955aa2e4d5b0fd6ebd57ff9715c07b0b # v2.73.0
        with:
          tool: cross # cross installs the latest rust toolchain

      # No Rust cache is provided, to avoid cache poisoning attack.

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - uses: goat-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      # For cargo-zigbuild in musl builds.
      - uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        if: ${{ contains(matrix.target, 'musl') }}
        with:
          version: 0.13.0

      - name: Setup OpenHarmony SDK
        if: ${{ contains(matrix.target, 'ohos') }}
        uses: Boshen/setup-ohos-sdk@edb865a89a712f1f15dbad932dfa9cfce849d95c # v1.0.0

      - name: Build goatlint for node.js
        working-directory: apps/goatlint
        run: ${{ matrix.build }}

      - name: Build Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') && !contains(matrix.target, 'riscv64gc-unknown-linux-musl') }}
        run: cross build --release -p goatlint --features allocator --target=${{ matrix.target }}

      - name: Build Rust binary (zigbuild)
        if: ${{ contains(matrix.target, 'riscv64gc-unknown-linux-musl') }}
        run: |
          pip3 install cargo-zigbuild
          cargo zigbuild --release -p goatlint --features allocator --target=${{ matrix.target }}

      - name: Upload NAPI artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: goatlint-bindings-${{ matrix.target }}
          path: |
            apps/goatlint/src-js/*.node
            apps/goatlint/src-js/*.wasm

      # The binaries are zipped to fix permission loss https://github.com/actions/upload-artifact#permission-loss
      - name: Archive Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') }}
        uses: ./.github/actions/archive-binary
        with:
          source_path: target/${{ matrix.target }}/release/goatlint${{ runner.os == 'Windows' && '.exe' || '' }}
          binary_name: goatlint-${{ matrix.target }}${{ runner.os == 'Windows' && '.exe' || '' }}
          archive_name: rust-goatlint-${{ matrix.target }}

      # For github release
      - name: Upload Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: rust-goatlint-${{ matrix.target }}
          path: |
            rust-goatlint-**.zip
            rust-goatlint-**.tar.gz

  build-goatlint-freebsd:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    name: Build Oxlint FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - name: Build
        id: build
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: "14.2"
          memory: 8G
          cpu_count: 3
          environment_variables: "DEBUG RUSTUP_IO_THREADS"
          shell: bash
          run: |
            sudo pkg install -y -f curl libnghttp2 node22 npm cmake ca_root_nss
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            source "$HOME/.cargo/env"
            echo "~~~~ rustc --version ~~~~"
            rustc --version
            echo "~~~~ node -v ~~~~"
            node -v
            pwd
            ls -lah
            whoami
            env
            export COREPACK_INTEGRITY_KEYS=0
            sudo corepack enable
            pnpm install --ignore-scripts # postinstall: The current platform (freebsd) and architecture (x64) is not supported.
            cd apps/goatlint
            pnpm run build-napi-release --target x86_64-unknown-freebsd
            cd ../..
            cargo build --release -p goatlint --features allocator --target=x86_64-unknown-freebsd
            rm -rf node_modules
            rm -rf target/x86_64-unknown-freebsd/release/build
            rm -rf target/x86_64-unknown-freebsd/release/deps
            rm -rf target/x86_64-unknown-freebsd/release/incremental

      - name: Upload NAPI artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: goatlint-bindings-x86_64-unknown-freebsd
          path: apps/goatlint/src-js/*.node

      - name: Archive Rust binary
        uses: ./.github/actions/archive-binary
        with:
          source_path: target/x86_64-unknown-freebsd/release/goatlint
          binary_name: goatlint-x86_64-unknown-freebsd
          archive_name: rust-goatlint-x86_64-unknown-freebsd

      - name: Upload Rust binary
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: rust-goatlint-x86_64-unknown-freebsd
          path: |
            rust-goatlint-**.zip
            rust-goatlint-**.tar.gz

  publish-goatlint:
    name: Publish Oxlint
    needs: [check, build-goatlint, build-goatlint-freebsd]
    runs-on: ubuntu-slim
    permissions:
      id-token: write # for `pnpm publish --provenance`
    env:
      package_path: npm/goatlint
      plugins_package_path: npm/goatlint-plugins
      plugin_eslint_package_path: npm/goatlint-plugin-eslint
      npm_dir: npm/goatlint-release
      PUBLISH_FLAGS: "--provenance --access public --no-git-checks"
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: artifacts
          pattern: goatlint-bindings-*

      - uses: goat-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - name: Generate goatlint JS build
        working-directory: apps/goatlint
        run: pnpm run build-js

      - run: mkdir -p ${npm_dir}

      - run: pnpm napi create-npm-dirs --package-json-path ${package_path}/package.json --npm-dir ${npm_dir}

      - run: pnpm napi artifacts --package-json-path ${package_path}/package.json --build-output-dir apps/goatlint/src-js --npm-dir ${npm_dir}

      - name: Copy dist files to npm package
        run: cp -r apps/goatlint/dist npm/goatlint/dist

      - name: Copy dist files to @goatlint/plugins npm package
        run: |
          cp apps/goatlint/dist-pkg-plugins/* ${plugins_package_path}/

      - name: Copy dist files to goatlint-plugin-eslint npm package
        run: |
          cp -r apps/goatlint/dist-pkg-plugin-eslint/. ${plugin_eslint_package_path}/

      - run: npm install -g npm@latest # For trusted publishing support

      - name: Check Publish
        run: |
          node .github/scripts/check-npm-packages.js "${npm_dir}/*" "${package_path}"
          node .github/scripts/check-npm-packages.js "${plugins_package_path}"
          node .github/scripts/check-npm-packages.js "${plugin_eslint_package_path}"

      - name: Trusted Publish
        run: |
          # Trusted publishing is configured, publish token is not required.
          # Publish sub-packages and adds `optionalDependencies` to main package.
          pnpm napi pre-publish --no-gh-release -t npm --package-json-path ${package_path}/package.json --npm-dir ${npm_dir}
          # Publish `goatlint` package
          bash .github/scripts/publish-if-needed.sh ${package_path} ${PUBLISH_FLAGS}
          # Publish `@goatlint/plugins` package
          bash .github/scripts/publish-if-needed.sh ${plugins_package_path} ${PUBLISH_FLAGS}
          # Publish `goatlint-plugin-eslint` package
          bash .github/scripts/publish-if-needed.sh ${plugin_eslint_package_path} ${PUBLISH_FLAGS}

  build-goatfmt:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            build: pnpm run build-napi-release --target x86_64-pc-windows-msvc

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            build: pnpm run build-napi-release --target aarch64-pc-windows-msvc

          - os: windows-latest
            target: i686-pc-windows-msvc
            build: pnpm run build-napi-release --target i686-pc-windows-msvc

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: pnpm run build-napi-release --target x86_64-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: pnpm run build-napi-release --target aarch64-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: pnpm run build-napi-release --target armv7-unknown-linux-gnueabihf --use-napi-cross

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: pnpm run build-napi-release --target x86_64-unknown-linux-musl -x

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: pnpm run build-napi-release --target aarch64-unknown-linux-musl -x

          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            build: pnpm run build-napi-release --target armv7-unknown-linux-musleabihf -x

          - os: macos-latest
            target: x86_64-apple-darwin
            build: pnpm run build-napi-release --target x86_64-apple-darwin

          - os: macos-latest
            target: aarch64-apple-darwin
            build: pnpm run build-napi-release --target aarch64-apple-darwin

          - os: ubuntu-latest
            target: aarch64-linux-android
            build: pnpm run build-napi-release --target aarch64-linux-android

          - os: ubuntu-latest
            target: armv7-linux-androideabi
            build: pnpm run build-napi-release --target armv7-linux-androideabi

          - os: ubuntu-latest
            target: aarch64-unknown-linux-ohos
            build: pnpm run build-napi-release --target aarch64-unknown-linux-ohos

          - os: ubuntu-latest
            target: powerpc64le-unknown-linux-gnu
            build: pnpm run build-napi-release --target powerpc64le-unknown-linux-gnu --use-napi-cross

          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
            build: |
              sudo apt-get update
              sudo apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu -y
              export TARGET_CC=riscv64-linux-gnu-gcc
              export CXX=riscv64-linux-gnu-g++
              pnpm run build-napi-release --target riscv64gc-unknown-linux-gnu

          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-musl
            build: pnpm run build-napi-release --target riscv64gc-unknown-linux-musl -x

          - os: ubuntu-latest
            target: s390x-unknown-linux-gnu
            build: export CFLAGS="-fuse-ld=lld" && pnpm run build-napi-release --target s390x-unknown-linux-gnu --use-napi-cross

    name: Build Oxfmt ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      TARGET_CC: clang # for mimalloc
    defaults:
      run:
        shell: bash
    steps:
      - if: ${{ contains(matrix.os, 'windows') }}
        run: git config --system core.longpaths true

      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Install cross
        uses: taiki-e/install-action@7a562dfa955aa2e4d5b0fd6ebd57ff9715c07b0b # v2.73.0
        with:
          tool: cross # cross installs the latest rust toolchain

      # No Rust cache is provided, to avoid cache poisoning attack.

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - uses: goat-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      # For cargo-zigbuild in musl builds.
      - uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        if: ${{ contains(matrix.target, 'musl') }}
        with:
          version: 0.13.0

      - name: Setup OpenHarmony SDK
        if: ${{ contains(matrix.target, 'ohos') }}
        uses: Boshen/setup-ohos-sdk@edb865a89a712f1f15dbad932dfa9cfce849d95c # v1.0.0

      - name: Build goatfmt for node.js
        working-directory: apps/goatfmt
        run: ${{ matrix.build }}

      - name: Build Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') && !contains(matrix.target, 'riscv64gc-unknown-linux-musl') }}
        run: cross build --release -p goatfmt --no-default-features --features allocator --target=${{ matrix.target }}

      - name: Build Rust binary (zigbuild)
        if: ${{ contains(matrix.target, 'riscv64gc-unknown-linux-musl') }}
        run: |
          pip3 install cargo-zigbuild
          cargo zigbuild --release -p goatfmt --no-default-features --features allocator --target=${{ matrix.target }}

      - name: Upload NAPI artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: goatfmt-bindings-${{ matrix.target }}
          path: |
            apps/goatfmt/src-js/*.node
            apps/goatfmt/src-js/*.wasm

      # The binaries are zipped to fix permission loss https://github.com/actions/upload-artifact#permission-loss
      - name: Archive Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') }}
        uses: ./.github/actions/archive-binary
        with:
          source_path: target/${{ matrix.target }}/release/goatfmt${{ runner.os == 'Windows' && '.exe' || '' }}
          binary_name: goatfmt-${{ matrix.target }}${{ runner.os == 'Windows' && '.exe' || '' }}
          archive_name: rust-goatfmt-${{ matrix.target }}

      # For github release
      - name: Upload Rust binary
        if: ${{ !contains(matrix.target, 'wasm') && !contains(matrix.target, 'android') && !contains(matrix.target, 'ohos') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: rust-goatfmt-${{ matrix.target }}
          path: |
            rust-goatfmt-**.zip
            rust-goatfmt-**.tar.gz

  build-goatfmt-freebsd:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    name: Build Oxfmt FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - name: Build
        id: build
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: "14.2"
          memory: 8G
          cpu_count: 3
          environment_variables: "DEBUG RUSTUP_IO_THREADS"
          shell: bash
          run: |
            sudo pkg install -y -f curl libnghttp2 node22 npm cmake ca_root_nss
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            source "$HOME/.cargo/env"
            echo "~~~~ rustc --version ~~~~"
            rustc --version
            echo "~~~~ node -v ~~~~"
            node -v
            pwd
            ls -lah
            whoami
            env
            export COREPACK_INTEGRITY_KEYS=0
            sudo corepack enable
            pnpm install --ignore-scripts # postinstall: The current platform (freebsd) and architecture (x64) is not supported.
            cd apps/goatfmt
            pnpm run build-napi-release --target x86_64-unknown-freebsd
            cd ../..
            cargo build --release -p goatfmt --no-default-features --features allocator --target=x86_64-unknown-freebsd
            rm -rf node_modules
            rm -rf target/x86_64-unknown-freebsd/release/build
            rm -rf target/x86_64-unknown-freebsd/release/deps
            rm -rf target/x86_64-unknown-freebsd/release/incremental

      - name: Upload NAPI artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: goatfmt-bindings-x86_64-unknown-freebsd
          path: apps/goatfmt/src-js/*.node

      - name: Archive Rust binary
        uses: ./.github/actions/archive-binary
        with:
          source_path: target/x86_64-unknown-freebsd/release/goatfmt
          binary_name: goatfmt-x86_64-unknown-freebsd
          archive_name: rust-goatfmt-x86_64-unknown-freebsd

      - name: Upload Rust binary
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          if-no-files-found: error
          name: rust-goatfmt-x86_64-unknown-freebsd
          path: |
            rust-goatfmt-**.zip
            rust-goatfmt-**.tar.gz

  publish-goatfmt:
    name: Publish Oxfmt
    needs: [check, build-goatfmt, build-goatfmt-freebsd]
    runs-on: ubuntu-slim
    permissions:
      id-token: write # for `pnpm publish --provenance`
    env:
      package_path: npm/goatfmt
      npm_dir: npm/goatfmt-release
      PUBLISH_FLAGS: "--provenance --access public --no-git-checks"
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: artifacts
          pattern: goatfmt-bindings-*

      - uses: goat-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - name: Generate goatfmt JS build
        working-directory: apps/goatfmt
        run: pnpm run build-js

      - run: mkdir -p ${npm_dir}

      - run: pnpm napi create-npm-dirs --package-json-path ${package_path}/package.json --npm-dir ${npm_dir}

      - run: pnpm napi artifacts --package-json-path ${package_path}/package.json --build-output-dir apps/goatfmt/src-js --npm-dir ${npm_dir}

      - name: Copy dist files to npm package
        run: cp -r apps/goatfmt/dist npm/goatfmt/dist

      - run: npm install -g npm@latest # For trusted publishing support

      - name: Check Publish
        run: node .github/scripts/check-npm-packages.js "${npm_dir}/*" "${package_path}"

      - name: Trusted Publish
        run: |
          # Trusted publishing is configured, publish token is not required.
          # Publish sub-packages and adds `optionalDependencies` to main package.
          pnpm napi pre-publish --no-gh-release -t npm --package-json-path ${package_path}/package.json --npm-dir ${npm_dir}
          bash .github/scripts/publish-if-needed.sh ${package_path} ${PUBLISH_FLAGS}

  github-release:
    name: GitHub Release
    needs:
      [
        check,
        build-goatlint,
        build-goatlint-freebsd,
        build-goatfmt,
        build-goatfmt-freebsd,
        publish-goatlint,
        publish-goatfmt,
      ]
    permissions:
      contents: write # for `gh release create`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          fetch-depth: 0 # for changelog
          persist-credentials: true

      - uses: goat-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          restore-cache: false
          tools: cargo-release-oxc

      - name: Generate changelog
        id: run
        run: |
          mkdir -p target
          cargo release-oxc changelog --release goatfmt --release goatlint
          {
            echo "## Table of Contents"
            echo ""
            echo "- [Oxlint v${NEEDS_CHECK_OUTPUTS_OXLINT_VERSION}](#goatlint-v${NEEDS_CHECK_OUTPUTS_OXLINT_VERSION})"
            echo "- [Oxfmt v${NEEDS_CHECK_OUTPUTS_OXFMT_VERSION}](#goatfmt-v${NEEDS_CHECK_OUTPUTS_OXFMT_VERSION})"
            echo ""
            echo "## Oxlint v${NEEDS_CHECK_OUTPUTS_OXLINT_VERSION}"
            cat ./target/OXLINT_CHANGELOG
            echo ""
            echo ""
            echo "## Oxfmt v${NEEDS_CHECK_OUTPUTS_OXFMT_VERSION}"
            cat ./target/OXFMT_CHANGELOG
          } > ./target/RELEASE_BODY.md
        env:
          NEEDS_CHECK_OUTPUTS_OXLINT_VERSION: ${{ needs.check.outputs.goatlint_version }}
          NEEDS_CHECK_OUTPUTS_OXFMT_VERSION: ${{ needs.check.outputs.goatfmt_version }}

      - name: tag goatlint and goatfmt
        env:
          NEEDS_CHECK_OUTPUTS_OXFMT_VERSION: ${{ needs.check.outputs.goatfmt_version }}
          NEEDS_CHECK_OUTPUTS_OXLINT_VERSION: ${{ needs.check.outputs.goatlint_version }}
        run: |
          git tag goatfmt_v${NEEDS_CHECK_OUTPUTS_OXFMT_VERSION} ${{ github.sha }}
          git tag goatlint_v${NEEDS_CHECK_OUTPUTS_OXLINT_VERSION} ${{ github.sha }}
          git push origin goatlint_v${NEEDS_CHECK_OUTPUTS_OXLINT_VERSION} goatfmt_v${NEEDS_CHECK_OUTPUTS_OXFMT_VERSION}

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ./release-artifacts
          pattern: rust-*
          merge-multiple: true

      - name: Remove rust- prefix from filenames
        run: |
          cd release-artifacts
          for file in rust-*; do
            mv "$file" "${file#rust-}"
          done
          ls

      - name: Create GitHub Release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_TAG: apps_v${{ needs.check.outputs.goatlint_version }}
          GIT_TARGET: ${{ github.sha }}
          TITLE: "goatlint v${{ needs.check.outputs.goatlint_version }} & goatfmt v${{ needs.check.outputs.goatfmt_version }}"
        run: gh release create ${GIT_TAG} ./release-artifacts/* --title "${TITLE}" --notes-file ./target/RELEASE_BODY.md --target ${GIT_TARGET}

      - uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645 # v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_OXC_RELEASES_CHANNEL }}
          embed-title: goatlint v${{ needs.check.outputs.goatlint_version }} & goatfmt v${{ needs.check.outputs.goatfmt_version }}
          embed-description: A new release is available! Check the changelog for details.
          embed-url: https://github.com/${{ github.repository }}/releases/tag/apps_v${{ needs.check.outputs.goatlint_version }}

      - name: wait 3 minutes for smoke test
        run: sleep 180s

  smoke:
    needs: [check, github-release]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: ubuntu-latest
            container: node:24-alpine # musl
          - os: macos-latest
    name: Smoke Test ${{ matrix.os }} ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Test
        # These commands should be run on these defaults:
        # - windows: pwsh
        # - ubuntu: bash
        # - alpine: sh
        # - macos: bash
        run: | # zizmor: ignore[template-injection]
          echo "" > test.js
          ldd --version || true
          npx goatfmt@${{ needs.check.outputs.goatfmt_version }} ./test.js
          npx goatlint@${{ needs.check.outputs.goatlint_version }} ./test.js

  bump:
    needs: [check, smoke]
    name: Bump goatlint dependents
    runs-on: ubuntu-slim
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - name: Bump goat-project/eslint-plugin-goatlint
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/eslint-plugin-goatlint
          workflow: bump_goatlint.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "version": "${{ needs.check.outputs.goatlint_version }}" }'

      - name: Bump goat-project/goatlint-migrate
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/goatlint-migrate
          workflow: bump_goatlint.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "version": "${{ needs.check.outputs.goatlint_version }}" }'

      - name: Bump goat-project/mirrors-goatlint
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/mirrors-goatlint
          workflow: main.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main

      - name: Bump goat-project/mirrors-goatfmt
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1.3.1
        with:
          repo: goat-project/mirrors-goatfmt
          workflow: main.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
