[package]
name = "goat_minifier"
version = "0.124.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/examples", "/src"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
test = true

[dependencies]
goat_allocator = { workspace = true }
goat_ast = { workspace = true }
goat_ast_visit = { workspace = true }
goat_compat = { workspace = true }
goat_data_structures = { workspace = true, features = ["stack"] }
goat_ecmascript = { workspace = true }
oxc_index = { workspace = true }
goat_mangler = { workspace = true }
goat_parser = { workspace = true }
goat_regular_expression = { workspace = true }
goat_semantic = { workspace = true }
goat_span = { workspace = true }
goat_str = { workspace = true }
goat_syntax = { workspace = true }
goat_traverse = { workspace = true }

cow-utils = { workspace = true }
itoa = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
goat_codegen = { workspace = true, features = ["sourcemap"] }
goat_parser = { workspace = true }
oxc_sourcemap = { workspace = true }

insta = { workspace = true }
javascript-globals = { workspace = true }
pico-args = { workspace = true }
